import type { Task } from './types';

export const sampleTasks: Task[] = [
  {
    id: '1',
    title: '協助採買生活用品',
    description: '需要人幫忙到超市採買馬鈴薯、牛奶與衛生紙。',
    category: '跑腿代辦',
    reward: 150,
    location: '台北市信義區松高路 12 號',
    posterName: '林小姐',
    posterTrustScore: 4,
    requiresCertification: false,
    posterIsCertified: false,
    status: 'Open',
    estimatedDuration: '1小時',
  },
  {
    id: '2',
    title: '水龍頭漏水簡易維修',
    description: '浴室水龍頭有些漏水，需協助換墊片。工具已備齊。',
    category: '簡易維修',
    reward: 500,
    location: '新北市板橋區文化路一段 100 號',
    posterName: '張先生',
    posterTrustScore: 5,
    requiresCertification: false,
    posterIsCertified: true,
    posterCertificationOrg: '台北市社會福利聯盟',
    status: 'Open',
    estimatedDuration: '2小時',
  },
  {
    id: '3',
    title: '長者陪伴聊天',
    description: '周日下午陪伴家中長者聊天與散步約 2 小時。',
    category: '陪伴關懷',
    reward: 300,
    location: '台中市西屯區台灣大道三段 50 號',
    posterName: '陳太太',
    posterTrustScore: 5,
    requiresCertification: false,
    posterIsCertified: false,
    status: 'Open',
    estimatedDuration: '2小時',
    deadline: '2025-10-31T17:00'
  },
  {
    id: '4',
    title: '整理房間與簡單打掃',
    description: '需要幫忙整理臥室與客廳，包含吸塵與擦拭。',
    category: '家務助理',
    reward: 400,
    location: '高雄市左營區自由三路 88 號',
    posterName: '王阿姨',
    posterTrustScore: 3,
    requiresCertification: false,
    posterIsCertified: false,
    status: 'Open',
    estimatedDuration: '半天',
  }
];
